version: 0.0
os: linux
files:
  - source: jar/netty-introduction.jar
    destination: /opt/nettyapp/
  - source: jar/libs/
    destination: /opt/nettyapp/libs/
  - source: run.sh
    destination: /opt/nettyapp/
hooks:
  ApplicationStop:
    - location: deployment_scripts/stop.sh
  AfterInstall:
    - location: deployment_scripts/deploy.sh
  ApplicationStart:
    - location: deployment_scripts/start.sh