version: 0.0
os: linux
files:
  - source: "*.jar"
    destination: /opt/nettyapp/
  - source: "lib/*.jar"
    destination: /opt/nettyapp/lib/
  - source: run.sh
    destination: /opt/nettyapp/
hooks:
  BeforeInstall:
    - location: deployment_scripts/unzip_resource_bundle.zip
  ApplicationStop:
    - location: deployment_scripts/stop.sh
  AfterInstall:
    - location: deployment_scripts/deploy.sh
  ApplicationStart:
    - location: deployment_scripts/start.sh